### ISSUE TITLE
"A JavaScript error occurred in the main process" on macOS Monterey with 18.5 Beta 3 

### ISSUE THREAD

**Issue by jjsawdon** [VilleOlof/Toolbox#1]
**Describe the bug**
Unable to launch Toolbox.

**To Reproduce**
On macOS 12.6.6, Toolbox fails to launch and Electron throws this error:
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Toolbox/Electron/../AppSettings.json'
at Object.openSync (fs.js:440:3)
at Object.func (electron/js2c/asar.js:140:31)
at Object.func [as openSync] (electron/js2c/asar.js:140:31)
at Object.readFileSync (fs.js:342:35)
at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
at Object.<anonymous> (/Library/Application Support/Blackmagic Design/DaVinci Resolve/Workflow Integration Plugins/Toolbox/Electron/main.js:7:35)
at Module._compile (internal/modules/cjs/loader.js:968:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
at Module.load (internal/modules/cjs/loader.js:816:32)

**System:**
 - OS: macOS 12.6.6
 - Resolve: Studio 18.5 beta 3
 - Toolbox Version: 1.0.6

**Comment by VilleOlof** [comment]
Weird, tested this in resolve beta 3 and toolbox 1.0.6 earlier and it did at least start.

Does the 'AppSettings.json' file exist in the root directory of the workflow integration?

**Comment by jjsawdon** [comment]
Ah, that was it. Might wanna either include a default or some note in the install instructions.
